### ISSUE TITLE
Learning CSS 

### ISSUE THREAD

**Issue by sagargg-zz** [Zaymes/html-basic#1]
Good work @Zaymes . 
Now i'll assume that you did  know some what HTML tags and attribute.
Again can you go through this tutorial. [https://www.w3schools.com/css/default.asp](https://www.w3schools.com/css/default.asp) 

### Tasks 
* [x] Understand and differentiate external, internal and inline css. 
* [x] Understand  about selector, eg, id selector, class selector, hover,  active  before, after  etc. 
* [x] Understand and differentiate css property and values. deeply  understand on common property like  margin, padding color, font, width height etc.
* [x] write down some notes about css. Same like HTML you did last time. 
`eg`: font-familty: 'arial';  Used to specify the font type on the components.
* [x] Implement external, internal and inline css on  this html project. 
* [x] Implement different css property  on  this html project. 

**Note**  You  shouldn't have to remember all the property for now. no one  remember all. But need to have some basic idea of how the styling is produces on the html  page. 
You have to stick to the css learning this week. Because there are lot more thing's you need to explorer. 

### Homework 
- Try to develop below page implementing css and html only.
-  for Image pull out from google. 
-  Apply similar fonts colors and image etc. 

![Screen Shot 2019-12-07 at 2 38 56 PM](https://user-images.githubusercontent.com/11631101/70371755-54673b00-18ff-11ea-8d1b-c1c047ef670b.png)

**Comment by Zaymes** [comment]
@sagargg  Notes for CSS are in https://hackmd.io/@CkFtLDzpSaaJ-ylR9kXY_A/HkHR_K5ar and page above is developed.

**Comment by sagargg-zz** [comment]
@Zaymes  can you share the screenshot of page . 
also check task like below eg. 
- [x] Done task

**Comment by Zaymes** [comment]
@sagargg 
![Screenshot (43)](https://user-images.githubusercontent.com/28755348/71082611-7f804300-21b9-11ea-8c5a-978adb589a22.png)
